### ISSUE TITLE
Uncaught TypeError: styleElement.register is not a function

### ISSUE THREAD

**Issue by nicktsai1026** [LostInBrittany/granite-bootstrap#11]
Hi, bootstrap works in chrome website but I got this error when I use firefox and chrome inspect device mobile mode.

<img width="507" alt="screen shot 2019-02-20 at 4 26 55 pm" src="https://user-images.githubusercontent.com/29011813/53079106-aede0900-3530-11e9-9dd9-06db610a3109.png">

dependencies: "@granite-elements/granite-bootstrap": "^4.1.1-1"

need help, please!

**Comment by ShahidNaumanTEO** [comment]
**Object doesn't support property or method 'register'** in Microsoft Edge 44
