### ISSUE TITLE
Updated Polymer JS library to latest. The application is throwing DOMException.

### ISSUE THREAD

**Issue by ShahidNaumanTEO** [LostInBrittany/granite-bootstrap#13]
Uncaught DOMException: Failed to execute 'define' on 'CustomElementRegistry': the name "dom-module" has already been used with this registry
    at http://localhost:8081/node_modules/@granite-elements/granite-bootstrap/node_modules/@polymer/polymer/lib/elements/dom-module.js:176:16

I have updated the node packages to latest.
@polymer/polymer  ^3.3.0  →   ^**3.3.1**
@webcomponents/webcomponentsjs  ^2.3.0  →   ^**2.4.0**

**Comment by LostInBrittany** [comment]
Ouch :S 

Looking at it now!

**Comment by LostInBrittany** [comment]
Where are you having this error? In your own application or in the demo of granite-bootstrap?
The error you see is that some component is loading the polymer library not from the main node_modules folder, but from a node_modules subfolder inside granite-bootstrap, and that is a bad practice with web components, as you can create collisions in the registry (i.e. your error).

**Comment by ShahidNaumanTEO** [comment]
Downgrading the `granite-bootstrap` to release **`4.1.1-0`** resolved the issue. But the newer versions breaks the application.

I have double-checked my application. None of my component is referring to the `node_modules` sub-folder inside `granite-bootstrap`

**Comment by LostInBrittany** [comment]
I guess you cannot send me or publish anywhere the code you're using, I suspect a problem with imports :( 

If sending or publishing the code isn't possible, I can try some other, dependence-less approach. 
Would you be willing to try it?

**Comment by LostInBrittany** [comment]
I have removed the Polymer dependency, using directly lit-html to render the style module template.
Could you please try the `@granite-elements/granite-bootstrap@4.3.1-2` version and telling me how does it work for you?

**Comment by ShahidNaumanTEO** [comment]
This is breaking the other parts of my application. I'll stick to the downgraded version, for now.

**Comment by LostInBrittany** [comment]
I would love to know what it is breaking. I have tested it in several Polymer-based apps of mine without any problem... Could you please share some details?

**Comment by LostInBrittany** [comment]
If it's still a problem, please re-open it with the details! :)
