### ISSUE TITLE
Could not find style data in module named granite-bootstrap

### ISSUE THREAD

**Issue by cosmicdreams** [LostInBrittany/granite-bootstrap#2]
When I follow your installation instructions I receive the warning : ```Could not find style data in module named granite-bootstrap```

Is this working?

**Comment by ghost** [comment]
I think you have to change the 'old' 'is' attribute, in the source code, with 'id'. This worked for me.
dom-module is="granite-bootstrap"
becomes
dom-module id="granite-bootstrap"

**Comment by LostInBrittany** [comment]
Yeah, this old component hasn't still be actualized to Polymer 1.9 / 2.x hybrid.
I'm doing it now...
