### ISSUE TITLE
Margins in row

### ISSUE THREAD

**Issue by ghost** [LostInBrittany/granite-bootstrap#3]
To allow for correct row alignments (rightmost and leftmost columns), there are in bootstrap two settings (in row):
    margin-right: -15px;
    margin-left: -15px;
for rows, that look to have no effect in shadow roots... :-(

**Comment by LostInBrittany** [comment]
Ouch, not cool!
Can you please show me an example, a JSFiddle/Codepen/Gist ?
I'll try to fix it!

**Comment by LostInBrittany** [comment]
Hi! Can I close this one? Still having the problem?

**Comment by ghost** [comment]
I remember that I solved in some other way, so I don't know anymore... sorry...
A
