### ISSUE TITLE
Could not find style data in module.

### ISSUE THREAD

**Issue by amanshu-kataria** [LostInBrittany/granite-bootstrap#4]
I'm using granite-bootstrap with Polymer 2. I followed the instructions to use granite-bootstrap but it doesn't work. I'm getting the following warning:

![capture](https://user-images.githubusercontent.com/13014093/28236937-3e0057f8-6951-11e7-80a7-dda73be309a0.PNG)

**Comment by amanshu-kataria** [comment]
@LostInBrittany need help here please.

**Comment by LostInBrittany** [comment]
OK, have you tried the demo? Does it work for you?
I'm going to test everything from scratch and see if there is a problem on my side.

**Comment by LostInBrittany** [comment]
Démo online on : https://lostinbrittany.github.io/granite-bootstrap/components/granite-bootstrap/demo/

**Comment by amanshu-kataria** [comment]
@LostInBrittany I tried the demo, it doesn't work as well. Shows the same warning here too.

**Comment by LostInBrittany** [comment]
What browser are you using ? Version, and OS, please, I will try to
reproduce.

**Comment by amanshu-kataria** [comment]
@LostInBrittany 
Browser: Chrome
Version 59.0.3071.115
OS: Windows 10
I'm not using any other browser because I'm developing extension for Chrome.

**Comment by LostInBrittany** [comment]
OK, I really don't  understand now... 

Here you have the demo on my Chromium  59.0.3071.109 (Developer Build) Built on Ubuntu , running on Ubuntu 17.04 (64-bit):

![image](https://user-images.githubusercontent.com/726476/28319029-0254288c-6bcd-11e7-8fdf-b133fc3b4514.png)

And here on a Firefox 55.0b9 running on Ubuntu 17.04 (64-bit):
![image](https://user-images.githubusercontent.com/726476/28319558-7d8ddf38-6bce-11e7-9ce1-d945c3f95cb4.png)
 
I have no Windows 10 here right now, but it would be the first time I find that kind of difference between a Chrome on Windows and on Linux. I will try  on a windows machine tonight at home to be sure...

**Comment by amanshu-kataria** [comment]
The demo works fine on Plunkr. But when I run the same code on a Polymer project it doesn't.


________________________________

**Comment by LostInBrittany** [comment]
Can you share your Polymer project? I need to be able to reproduce if you
want me to help...

**Comment by amanshu-kataria** [comment]
@LostInBrittany the demo is working. But when I run the demo code on a Polymer project it doesn't work. Sorry about not clearing it.

**Comment by LostInBrittany** [comment]
Please try to be sure that the version is the right one by setting it specifically  on your `bower.json` using:

```
"granite-bootstrap":"LostInBrittany/granite-bootstrap#3.3.7-4" 
```

**Comment by amanshu-kataria** [comment]
@LostInBrittany  it's `"granite-bootstrap": "LostInBrittany/granite-bootstrap#^3.3.7"`

**Comment by LostInBrittany** [comment]
Please use  `"granite-bootstrap":"LostInBrittany/granite-bootstrap#3.3.7-4" `, delete your `bower_components` and do a new `bower install`, and tell me if it works :)

**Comment by amanshu-kataria** [comment]
@LostInBrittany it worked. Thanks a lot. :)

**Comment by LostInBrittany** [comment]
YES ! :) :)
